server:
  port: 8001

spring:
  application:
    name: cloud-payment-srvice
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.99:3306/provider-payment8001?useSSL=false&serverTimezone=UTC
    username: lichy
    password: lichy

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.lichy.springcloud.entites


logging:
  level:
    com.lichy.springcloud.dao: DEBUG

eureka:
  client:
    # 向中心注册自己
    register-with-eureka: true
    # 是否去检索服务
    fetch-registry: true
    service-url:
      # 与Eureka Server 交互地址
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: cloud-payment-srvice1
    prefer-ip-address: true