server:
  port: 9527

spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh #路由ID，唯一，建议配合服务名
          uri: lb://cloud-payment-srvice # 匹配后的路由地址
          predicates:
            - Path=/payment/get/**   # 断言，路径向匹配的路由
        - id: payment_routh2 #路由ID，唯一，建议配合服务名
          uri: lb://cloud-payment-srvice # 匹配后的路由地址
          predicates:
            - Path=/payment/lb/**   # 断言，路径向匹配的路由



eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    # 向中心注册自己
    register-with-eureka: true
    # 是否去检索服务
    fetch-registry: true
    service-url:
      # 与Eureka Server 交互地址
      defaultZone: http://eureka7001.com:7001/eureka