server:
  port: 8004

spring:
  application:
    name: cloud-payment-srvice
  cloud:
    zookeeper:
      connect-string: 192.168.1.99:2181,192.168.1.99:2182,192.168.1.99:2183
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.99:3306/provider-payment8001?useSSL=false&serverTimezone=UTC
    username: lichy
    password: lichy

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.lichy.springcloud.entites


logging:
  level:
    com.lichy.springcloud.dao: DEBUG
