server:
  port: 80


spring:
  application:
    name:  cloud-order-service

eureka:
  client:
    # 向中心注册自己
    register-with-eureka: false
    service-url:
      # 与Eureka Server 交互地址
      defaultZone: http://eureka7001.com:7001/eureka

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
logging:
  level:
    com.lichy.springcloud.service.PaymentFeignService: debug
feign:
  hystrix:
    enabled: true
